#include "ui/provenance.h"

#include <QDateTime>
#include <QPainter>
#include <algorithm>

#include "ui/theme.h"

namespace ui {

namespace {

// Section 6.2, worded once and reachable from one branch. Keeping it a
// file-local constant is what makes "exactly one place" structural: no other
// translation unit can reach it, so no other surface can grow a second copy.
const QString kLicenceCaveat = " Music made with it may not be licenseable.";

}  // namespace

QString provenance_text(const core::Provenance& provenance) {
    if (!provenance.ai_origin()) return "Made by hand";
    QString when = QDateTime::fromSecsSinceEpoch(provenance.at).toString("yyyy-MM-dd");
    QString who = QString::fromStdString(provenance.source);
    // Only generative-model output carries the caveat. An Assistant edit of
    // the user's own material is AI-authored, not AI-generated, and telling
    // its author otherwise would retract the section 6.1 promise (ADR-062).
    if (provenance.generative_output())
        return QString("AI-generated by %1 on %2.").arg(who, when) + kLicenceCaveat;
    return QString("Made with the Assistant (%1) on %2.").arg(who, when);
}

void paint_provenance_mark(QPainter& painter, const QRect& corner) {
    painter.save();
    painter.setRenderHint(QPainter::Antialiasing, true);
    painter.setPen(Qt::NoPen);
    painter.setBrush(theme::kAccent);
    painter.drawRoundedRect(corner, 2, 2);
    QFont font = painter.font();
    font.setPixelSize(std::max(6, corner.height() - 2));
    font.setBold(true);
    painter.setFont(font);
    painter.setPen(theme::kCanvas);
    painter.drawText(corner, Qt::AlignCenter, "AI");
    painter.restore();
}

}  // namespace ui
