// The section 6.3 provenance mark, drawn the same way wherever an
// AI-generated Sample or Pattern appears: a small logo in its corner, and
// the provenance stated in words when it is opened up. Derived from
// Provenance on every paint, never stored by the UI.
#pragma once

#include <QDateTime>
#include <QPainter>
#include <QString>

#include "core/entities.h"
#include "ui/theme.h"

namespace ui::provenance {

inline QString text(const core::Provenance& provenance) {
    if (provenance.is_human()) return "Made by hand";
    QString when = QDateTime::fromSecsSinceEpoch(provenance.generated_at).toString("yyyy-MM-dd");
    return QString("AI-generated by %1 on %2. Music made with it may not be licenseable.")
        .arg(QString::fromStdString(provenance.generated_by), when);
}

// The small logo in the corner of an AI-generated entity.
inline void paint_mark(QPainter& painter, const QRect& corner) {
    painter.save();
    painter.setRenderHint(QPainter::Antialiasing, true);
    painter.setPen(Qt::NoPen);
    painter.setBrush(theme::kAccent);
    painter.drawRoundedRect(corner, 2, 2);
    QFont font = painter.font();
    font.setPixelSize(corner.height() < 10 ? 7 : 8);
    font.setBold(true);
    painter.setFont(font);
    painter.setPen(theme::kCanvas);
    painter.drawText(corner, Qt::AlignCenter, "AI");
    painter.restore();
}

}  // namespace ui::provenance
