#include "ui/provenance.h"

#include <QDateTime>
#include <QPainter>
#include <algorithm>

#include "ui/theme.h"

namespace ui {

QString provenance_text(const core::Provenance& provenance) {
    if (provenance.is_human()) return "Made by hand";
    QString when = QDateTime::fromSecsSinceEpoch(provenance.generated_at).toString("yyyy-MM-dd");
    return QString("AI-generated by %1 on %2. Music made with it may not be licenseable.")
        .arg(QString::fromStdString(provenance.generated_by), when);
}

void paint_provenance_mark(QPainter& painter, const QRect& corner) {
    painter.save();
    painter.setRenderHint(QPainter::Antialiasing, true);
    painter.setPen(Qt::NoPen);
    painter.setBrush(theme::kAccent);
    painter.drawRoundedRect(corner, 2, 2);
    QFont font = painter.font();
    font.setPixelSize(std::max(6, corner.height() - 2));
    font.setBold(true);
    painter.setFont(font);
    painter.setPen(theme::kCanvas);
    painter.drawText(corner, Qt::AlignCenter, "AI");
    painter.restore();
}

}  // namespace ui
